import Head from "next/head";
import {useRouter} from "next/router";

export default function Home() {
  const router = useRouter();
  console.log(router.query);
  return (
    <>
      <Head>
        <title>Next js course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>ID {`${router.query.projectid}`}</main>
    </>
  );
}
